name: CD

on:
  push:
    tags:
      - v[0-9].[0-9]+.[0-9]+

jobs:
  web-assets-cd:
    name: Web Assets CD
    defaults:
      run:
        working-directory: web-assets
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: reggionick/s3-deploy@v3
        with:
          folder: web-assets/src
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          bucket-region: ${{ secrets.AWS_REGION }}
          delete-removed: true
          private: true
